CC_META = [
            'American Express',
            'Bankcard',
            'China T-Union',
            'Diners Club enRoute',
            'Diners Club International',
            'Diners Club United States & Canada',
            'Discover Card',
            'UkrCard',
            'RuPay',
            'InterPayment',
            'InstaPayment',
            'JCB',
            'Laser',
            'Maestro UK',
            'Maestro',
            'Dankort',
            'Mir',
            'NPS Pridnestrovie',
            'Mastercard',
            'Solo',
            'Switch',
            'Troy',
            'Visa',
            'Visa Electron',
            'UATP',
            'Verve',
            'LankaPay',
            'UzCard',
            'Humo',
            'GPN'
        ]